---
- hosts: citrix_adc
  gather_facts: false
  connection: local
  collections:
    - citrix.adc
  vars_files:
    - vars/vault.yaml

  tasks:
    - name: Create server1
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{ nitro_nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        nitro_protocol: http
        validate_certs: no

        state: present

        name: ans_server-1
        ipaddress: 192.168.1.101

    - name: Set service group
      citrix_adc_server:
        nsip: "{{ nitro_nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        nitro_protocol: http
        validate_certs: no

        state: present

        name: ans_server-2
        ipaddress: 192.168.1.102