---
- name: Create containers
  hosts:
    - dockerhost
  gather_facts: no
  tasks:
    - name: Create gitlab
      include_tasks:
        file: containers/gitlab.yml

    - name: Create watchtower
      include_tasks:
        file: containers/watchtower.yml
